# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100, verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87URL')),
                ('title', models.CharField(max_length=100, verbose_name=b'\xe6\x96\x87\xe7\xab\xa0\xe6\xa0\x87\xe9\xa2\x98')),
                ('content', models.TextField(null=True, verbose_name=b'\xe6\x96\x87\xe7\xab\xa0\xe5\x86\x85\xe5\xae\xb9')),
                ('created', models.CharField(max_length=100, verbose_name=b'\xe5\x8f\x91\xe8\xa1\xa8\xe6\x97\xb6\xe9\x97\xb4')),
                ('views', models.PositiveIntegerField(default=0, verbose_name=b'\xe9\x98\x85\xe8\xaf\xbb\xe6\x95\xb0')),
                ('comments', models.PositiveIntegerField(default=0, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe6\x95\xb0')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name=b'\xe5\x96\x9c\xe6\xac\xa2')),
                ('top', models.PositiveIntegerField(default=0, verbose_name=b'\xe6\x89\x93\xe8\xb5\x8f')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100, verbose_name=b'\xe6\x96\x87\xe7\xab\xa0\xe6\xa0\x87\xe9\xa2\x98')),
                ('artilce_url', models.CharField(max_length=100, verbose_name=b'\xe6\x96\x87\xe7\xab\xa0url')),
                ('user', models.CharField(max_length=100, verbose_name=b'\xe4\xbd\x9c\xe8\x80\x85')),
                ('user_url', models.CharField(max_length=100, verbose_name=b'\xe4\xbd\x9c\xe8\x80\x85url')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jianshu.ArticleDetail', verbose_name=b'\xe6\x96\x87\xe7\xab\xa0\xe8\xaf\xa6\xe7\xbb\x86\xe4\xbf\xa1\xe6\x81\xaf')),
            ],
        ),
    ]
