# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-23 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianshu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlelist',
            old_name='user',
            new_name='article_user',
        ),
        migrations.RenameField(
            model_name='articlelist',
            old_name='user_url',
            new_name='article_user_url',
        ),
        migrations.AlterField(
            model_name='articlelist',
            name='article_url',
            field=models.URLField(verbose_name=b'\xe6\x96\x87\xe7\xab\xa0URL'),
        ),
    ]
