# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-23 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianshu', '0002_auto_20160723_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='comments',
            field=models.CharField(max_length=100, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe6\x95\xb0'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='likes',
            field=models.CharField(max_length=100, verbose_name=b'\xe5\x96\x9c\xe6\xac\xa2'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='tip',
            field=models.CharField(max_length=100, verbose_name=b'\xe6\x89\x93\xe8\xb5\x8f'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='views',
            field=models.CharField(max_length=100, verbose_name=b'\xe9\x98\x85\xe8\xaf\xbb\xe6\x95\xb0'),
        ),
    ]
