# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jianshu', '0003_auto_20160723_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articledetail',
            old_name='article',
            new_name='article_abstract',
        ),
    ]
