# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jianshu', '0007_search_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='article',
            new_name='HotArticle',
        ),
    ]
