# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_likes',
            new_name='article_likes_count',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_views',
            new_name='article_views_counts',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_comments',
            new_name='public_comments_count',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_tip',
            new_name='total_rewards_count',
        ),
    ]
